
import React from 'react';

export enum ToolId {
  HOME = 'HOME',
  PASSWORD_GENERATOR = 'PASSWORD_GENERATOR',
  ENCODER = 'ENCODER',
  SPEED_TEST = 'SPEED_TEST',
  JSON_TOOLS = 'JSON_TOOLS',
  QR_GENERATOR = 'QR_GENERATOR',
  UNIT_CONVERTER = 'UNIT_CONVERTER',
  HASHER = 'HASHER',
  UUID_GENERATOR = 'UUID_GENERATOR',
  REGEX_TESTER = 'REGEX_TESTER',
  TEXT_TOOLS = 'TEXT_TOOLS',
  COLOR_CONVERTER = 'COLOR_CONVERTER',
  EPOCH_CONVERTER = 'EPOCH_CONVERTER',
  JWT_DECODER = 'JWT_DECODER',
  MARKDOWN_PREVIEW = 'MARKDOWN_PREVIEW',
  URL_PARSER = 'URL_PARSER',
  LOREM_IPSUM = 'LOREM_IPSUM',
  LIST_UTILS = 'LIST_UTILS',
  PERCENTAGE_CALC = 'PERCENTAGE_CALC',
  KEYCODE_INFO = 'KEYCODE_INFO',
  CSS_GRADIENT = 'CSS_GRADIENT',
  TEXT_DIFF = 'TEXT_DIFF',
  SYSTEM_MONITOR = 'SYSTEM_MONITOR',
  SQL_FORMATTER = 'SQL_FORMATTER',
  CRON_PARSER = 'CRON_PARSER',
  CHMOD_CALC = 'CHMOD_CALC',
  META_TAGS = 'META_TAGS',
  IMAGE_COMPRESSOR = 'IMAGE_COMPRESSOR',
  GIT_CHEATSHEET = 'GIT_CHEATSHEET',
  HTTP_STATUS = 'HTTP_STATUS',
  MIME_TYPES = 'MIME_TYPES',
  PORT_REFERENCE = 'PORT_REFERENCE',
  CSS_SHADOW = 'CSS_SHADOW',
  // New Tools
  POMODORO = 'POMODORO',
  STOPWATCH = 'STOPWATCH',
  ASPECT_RATIO = 'ASPECT_RATIO',
  BORDER_RADIUS = 'BORDER_RADIUS',
  BASE64_IMAGE = 'BASE64_IMAGE',
  CSV_JSON = 'CSV_JSON',
  USER_AGENT = 'USER_AGENT',
  SLUG_GENERATOR = 'SLUG_GENERATOR',
  XML_FORMATTER = 'XML_FORMATTER',
  TEXT_STYLER = 'TEXT_STYLER',
  CURL_BUILDER = 'CURL_BUILDER',
  ROMAN_NUMERALS = 'ROMAN_NUMERALS',
  PASS_STRENGTH = 'PASS_STRENGTH',
  RANDOM_NUMBER = 'RANDOM_NUMBER',
  LUHN_ALGO = 'LUHN_ALGO',
}

export interface ToolDefinition {
  id: ToolId;
  name: string;
  description: string;
  icon: React.ComponentType<{ className?: string; size?: number | string }>;
  color: string;
  iconColor: string;
}

export type EncodingType = 'base64' | 'url' | 'hex' | 'html' | 'radix';